import AuthProvider from "@/components/context/Auth";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { roboto } from "@/utils/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className="flex flex-col min-h-screen">
          <AuthProvider session={session!}>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
