import AuthProvider from "@/components/context/Auth";
import Confirmation from "@/components/common/Confirmation";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { lato, railway } from "@/utils/fonts";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={lato.className}>
        <AuthProvider session={session!}>
          <Confirmation />
          <ToastContainer />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
