export const AppRoute = {
  root: "/",
  about: "/",
  contact: "/",
  admin: "/admin",
  users: "/users",
  adminDashboard: "/admin/dashboard",
  adminCategory: "/admin/category",
  adminCategoryEdit: "/admin/category/edit-category",
  adminProducts: "/admin/products",
  adminColor: "/admin/colors",
  adminSize: "/admin/sizes",
  product: "/product",
  category: "/category",
};
